#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-wsproto
Version  : 1.0.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/2b/a4/aded0882f8f1cddd68dcd531309a15bf976f301e6a3554055cc06213c227/wsproto-1.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/2b/a4/aded0882f8f1cddd68dcd531309a15bf976f301e6a3554055cc06213c227/wsproto-1.0.0.tar.gz
Summary  : WebSockets state-machine based protocol implementation
Group    : Development/Tools
License  : MIT
Requires: pypi-wsproto-python = %{version}-%{release}
Requires: pypi-wsproto-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(dataclasses)
BuildRequires : pypi(h11)
BuildRequires : pypi(pluggy)
BuildRequires : pypi(py)
BuildRequires : pypi(pytest)
BuildRequires : pypi(tox)
BuildRequires : pypi(virtualenv)

%description
Pure Python, pure state-machine WebSocket implementation
        ========================================================

%package python
Summary: python components for the pypi-wsproto package.
Group: Default
Requires: pypi-wsproto-python3 = %{version}-%{release}

%description python
python components for the pypi-wsproto package.


%package python3
Summary: python3 components for the pypi-wsproto package.
Group: Default
Requires: python3-core
Provides: pypi(wsproto)
Requires: pypi(dataclasses)
Requires: pypi(h11)

%description python3
python3 components for the pypi-wsproto package.


%prep
%setup -q -n wsproto-1.0.0
cd %{_builddir}/wsproto-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641501795
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
